SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR $ENV{ARCH})

SET(cross_triple $ENV{CROSS_TRIPLE})
SET(cross_root $ENV{CROSS_ROOT})

SET(CMAKE_C_COMPILER $ENV{CC})
SET(CMAKE_CXX_COMPILER $ENV{CXX})

SET(CMAKE_C_FLAGS "-I ${cross_root}/include/")
SET(CMAKE_CXX_FLAGS "-I ${cross_root}/include/")

SET(CMAKE_FIND_ROOT_PATH ${cross_root} ${cross_root}/${cross_triple})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
SET(CMAKE_SYSROOT $ENV{CROSS_SYSROOT})